- Tests/PublishTests/Tests/HTMLGenerationTests.swift
Otherwise, tests will fail on case-sensitive file systems.
> HTMLGenerationTests: Use lower-case tag path

- Sources/PublishCLICore/WebsiteRunner.swift
Prefixes the console output of the hostname with `http://` so that one can cmd-click to open the page right from the terminal.
> Add HTTP prefix to runner console output

- Sources/Publish/Internal/MarkdownFileHandler.swift
- Tests/PublishTests/Tests/HTMLGenerationTests.swift
When you create an item in a nested folder (e.g., `/Content/blog/2019/03/article1.md`) Publish generates the item HTML at `/Output/blog/2019/03article1/index.html` instead of `/Output/blog/2019/03/article1/index.html`. This pull request fixes that issue.
> Fix path for nested items

- Sources/Publish/API/PublishingStep.swift
- Sources/Publish/Internal/SiteMapGenerator.swift
- Tests/PublishTests/Infrastructure/Item+Stubbable.swift
- Tests/PublishTests/Tests/SiteMapGenerationTests.swift
Use case:
I want to have a whole section which I do not want to be included in the SiteMap.
> Allow excluding section's path as well while generating SiteMap

- Sources/Publish/API/Website.swift
- Tests/PublishTests/Infrastructure/PublishTestCase.swift
- Tests/PublishTests/Tests/PluginTests.swift
When adding the Splash plugin to my deployment pipeline I noticed that the only thing I wanted to change to the default pipeline was installing the plugin. I tried installing it through the `additionalSteps` API but they are called too late so they don't come into play. 
I wasn't sure whether to change the implementation to call those steps prior to anything else so I added an additional `plugins` parameter. 
Also, I wasn't sure how to add proper unit tests for this because the default pipeline is currently not tested at all, but I'd be glad to look into this more.
> Allow plugins to be added to default pipeline

- Package.resolved
- Package.swift
- Sources/Publish/API/FeedConfiguration.swift
- Sources/Publish/API/PodcastAuthor.swift
- Sources/Publish/API/PodcastFeedConfiguration.swift
- Sources/Publish/API/PublishingContext.swift
- Sources/Publish/API/PublishingStep.swift
- Sources/Publish/API/RSSFeedConfiguration.swift
- Sources/Publish/API/Tag.swift
- Sources/Publish/Internal/Folder+Group.swift
- Sources/Publish/Internal/PodcastFeedGenerator.swift
- Sources/Publish/Internal/PublishingPipeline.swift
- Sources/Publish/Internal/RSSFeedGenerator.swift
- Sources/Publish/Internal/String+Normalized.swift
- Tests/PublishTests/Tests/DeploymentTests.swift
- Tests/PublishTests/Tests/ErrorTests.swift
- Tests/PublishTests/Tests/PodcastFeedGenerationTests.swift
- Tests/PublishTests/Tests/RSSFeedGenerationTests.swift
This change makes Publish reuse any previously generated RSS and podcast feeds in case no new items have been added, no existing ones have been modified, and the configuration for generating the given feed hasn’t changed.
This is made possible by series of other changes:
- `PodcastFeedConfiguration` is no longer a subclass of its RSS counterpart, instead, both are separate structs that share a new `FeedConfiguration` protocol - in order to be able to enforce some degree of consistency.
- Both feed configuration types have been made `Equatable` and `Codable` in order to persist and compare them to previous configs.
- `PublishingContext` now has a `lastGenerationDate` API, which is used to compare the last modified item against when the website was last generated.
- `PublishingContext` now …
> Reuse RSS/Podcast feeds if possible

- Sources/PublishCLICore/WebsiteRunner.swift
Turns out I didn't have `SimpleHTTPServer` readily available and was experiencing some silent failures. Just grabbing the error and reporting it.
I often use [serve](https://www.npmjs.com/package/serve), aside from the initial javascript shock would having a cli parameter on `run` to specify the http server help anyone?
> catching and reporting errors encountered in 'publish run'

- Sources/Publish/Internal/PodcastFeedGenerator.swift
- Sources/Publish/Internal/RSSFeedGenerator.swift
- Tests/PublishTests/Tests/PodcastFeedGenerationTests.swift
- Tests/PublishTests/Tests/RSSFeedGenerationTests.swift
When new items were added, even if those items don’t have a later modification date than the previous generated site, always re-generate all RSS and podcast feeds.
> RSS/Podcast feeds: Invalidate cache when item count changed

- Resources/FoundationTheme/styles.css
This change improves the default Foundation CSS in the following ways:
- Margin added between list items.
- Horizontal wrapper padding decreased to 20 pixels for small screens.
> Foundation theme: Slight tweaks to the default CSS

- Sources/PublishCLICore/CLI.swift
- Sources/PublishCLICore/WebsiteRunner.swift
On my mac the port 8000 was blocked, therefore I extended the run CLI command to support a dynamic config with the attributes "-p" and "--port".
Because the CLI seems to be lightweight I only introduced a command option for this specific usecase, but with enums etc. there could be the posibility of generally introducing options for existing CLI commands.
> Enable dynamic port configuration for run CLI command

- Package.resolved
- Package.swift
- Sources/PublishCLICore/WebsiteRunner.swift
This patch fixes a CLI bug that would cause the local web server started by `publish run` to keep running indefinitely. Now, the server is properly shut down whenever the CLI exits.
Error handling has also been improved, and in case there’s already a `localhost` server running on the same port, a much richer error message with suggestions will now be displayed:
```
❌ Failed to start local web server:
A localhost server is already running on port number 8000.
- Perhaps another 'publish run' session is running?
- Publish uses Python's SimpleHTTPServer, so to find any
running processes, you can use either Activity Monitor
or the 'ps' command and search for 'python'. You can then
terminate any previous process in order to start a new one.
```
> CLI: Stop local web server when ‘publish run’ exits

- README.md
Given the discussion on this in https://github.com/JohnSundell/Publish/pull/6, and my also discovering it the long way around, wanted to offer a quick tweak to the readme to clarify the local development and regeneration workflow. Might save some time for newcomers pending @JohnSundell's introduction of more automated solutions.
Thanks for a great project! 🙏🏽
> Update README with note on site regeneration

- Sources/Publish/Internal/MarkdownContentFactory.swift
- Tests/PublishTests/Tests/MarkdownTests.swift
This was briefly discussed in #21 
This allows metadata contain an override value for the path, to be used instead of the resource filename.
> Allow overriding of an item path in markdown metadata

- Sources/Publish/API/Path.swift
- Tests/PublishTests/Tests/PlotComponentTests.swift
This patch makes the `Path` type preserve any external URL that it contains when calculating its `absoluteString` property. This is done by whitelisting the `http://` and `https://` prefixes, in order to be able to do things like load external stylesheets through Publish’s built-in Plot components.
> Path: Preserve external URLs when generating absolute strings

- README.md
* **Fixed**: The example code for `.step(named: "Default section titles")` did not work due to a minor code order issue.
* **Pending**:  In one of the following code blocks, this publishing pipeline is presented:
```
try DeliciousRecipes().publish(using: [
.addMarkdownFiles(),
.copyResources(),
.addFavoriteItems(),
.addDefaultSectionTitles(),
.generateHTML(withTheme: .delicious),
.generateRSSFeed(including: [.recipes]),
.generateSiteMap()
])
```
The step `.addFavoriteItems()`has not been introduced before nor is it introduced later on. Is it planned to add an example for this publishing step, should I draft an example, or can this publishing step be removed?
> Correct example code in README

- Sources/Publish/API/DeploymentMethod.swift
- Tests/PublishTests/Tests/DeploymentTests.swift
Maybe because I was using multiple computers over Publish, I came across lots of deploying problems, sometimes I needed to `cd .publish/GitDeploy/.git` to know what's happening, this PR fix the error feeding.
> Deploy now can throw git message from stderr

- Tests/PublishTests/Tests/DeploymentTests.swift
This patch fixes a few minor issues with the recent patch to make Git deployment errors propagate better to the user:
- Improve test code formatting.
- Make the test a bit more robust, by checking the contents of the error.
> Git deployment: Error handling post-merge fixes

- Resources/FoundationTheme/styles.css
- Sources/Publish/API/Section.swift
This change adds a bit of margin between each section within the header of the built-in Foundation theme. It also increases the line height for those links to make them render nicely on smaller screens when a larger number of sections have been added, and makes the currently selected link underlined.
It also makes the default `title` of all sections become a capitalized version of their `rawValue`.
> Foundation+Section: Improve section rendering

- Documentation/HowTo/custom-markdown-metadata-values.md
The "header" in a markdown file is commonly known as Front Matter in many other static site generators. For people coming from other generators it would be useful to relate what Publish calls "metadata" to what they know as "front matter". It would also help for people that does a search about it.
I would also like to include a mention of this in the README but I don't think it fits anywhere in the current prose. 
Example of other well known generators using this wording:
- Gatsby https://www.gatsbyjs.org/docs/adding-markdown-pages/#frontmatter-for-metadata-in-markdown-files
- Jekyll https://jekyllrb.com/docs/front-matter/
- Hugo https://gohugo.io/content-management/front-matter/
> Mention front matter

- Sources/Publish/API/Item.swift
- Tests/PublishTests/Infrastructure/PublishTestCase.swift
- Tests/PublishTests/Infrastructure/WebsiteStub.swift
- Tests/PublishTests/Tests/HTMLGenerationTests.swift
- Tests/PublishTests/Tests/WebsiteTests.swift
When making a multi-word SectionID it is necessary to set the rawvalue explicitly to for more standard urls.
Doing this caused two folders to be created in Output. If the SectionID was `case exampleSection = "example-section"`, Output would contain `example-section/index.hml` and `exampleSection/actualContents-of-folder-in-Content`
> Fixed SectionID rawvalue bug in item.

- Sources/Publish/API/Theme+Foundation.swift
Was previously missing from the built-in Foundation theme.
> Foundation theme: Render content body for pages

- Sources/Publish/API/SectionMap.swift
- Tests/PublishTests/Infrastructure/LinuxCompatibility.swift
- Tests/PublishTests/Infrastructure/XCTestManifests.swift
- Tests/PublishTests/Tests/PublishingContextTests.swift
This change makes the order in which sections are iterated over predictable. Before, a dictionary value iterator was used, which doesn’t guarantee any particular order. Now, sections are always iterated over in the order their IDs were defined in the current site’s `Website.SectionID` enum.
(Also includes some minor tweaks to ensure that all tests run on Linux).
> SectionMap: Make iteration order predictable

- Sources/Publish/API/Item.swift
- Sources/Publish/API/ItemRSSProperties.swift
- Tests/PublishTests/Tests/PodcastFeedGenerationTests.swift
- Tests/PublishTests/Tests/RSSFeedGenerationTests.swift
This change adds a new `titleSuffix` property to `ItemRSSProperties` which, just like `titlePrefix`, enables a string to be attached to an item’s title when it’s being rendered as part of an RSS/podcast feed.
> RSS: Add option to specify title suffixes for items

- Documentation/HowTo/add-syntax-highlighting-with-pygments.md
- Documentation/README.md
Hi. Thank you for making Publish. 
I have made a plugin for syntax highlighting using Pygments, and added a How-to article about using the plugin. 
I hope it will help a little bit to the project.
Here is an example on my site built with Publish:
https://czj.pw/highlight
Cheers, 
Zhijin
> Added article about syntax highlight with Pygments

- Sources/PublishCLICore/WebsiteRunner.swift
When running `publish run`, pressing any key won't stop the server. Should make the instruction clearer.
> Make stop server instruction clear

- Sources/PublishCLICore/ProjectGenerator.swift
- Tests/PublishTests/Tests/CLITests.swift
Hey John. First of all, thanks for all the contributions you've been doing for the community. You're truly an inspiration for many of us :hats-off:
This PR does the following:
* while trailing digits aren't valid (according to the existing tests I found), digits in the middle of the string should be valid in my opinion. For example: `Give2Charity` shouldn't have the `2` removed.
* when removing invalid characters, as dashes or underscores, the following character is capitalized. For example, `blog.somename.com` becomes `BlogSomenameCom`. The same is valid for a space or any other non-alphanumeric character.
* converts `asSiteName` to a variable, as it makes more sense in this case than a function
I've added a test and modified one existing to match the new behavior.
> Improve asSiteName extension

- Sources/PublishCLICore/WebsiteRunner.swift
I currently have the `python` shell command bound to Python 3 on my system. The `SimpleHTTPServer` command has been deprecated in Python 3, in favor of `http.server` instead. This change calls the appropriate command depending on which version of Python is being run on the system.
Let me know if there are any changes or additions you'd like to see made. Thanks!
> Determine which Python server command to use based on Python version

- Sources/Publish/Internal/PublishingPipeline.swift
- Tests/PublishTests/Tests/FileIOTests.swift
Hi, I want copy hidden files from Resources folder (for example: .htaccess) to Output folder. Problem is that `PublishingPipeline.setUpFolders` not removes hidden files.
This PR fix the cleaning step. If you agree I also add hidden files copying to copy file publishing steps.
Copy hidden files can be done in many variants:
* automatic copy hidden files by modify `folder.files` to `folder.files.includingHidden` in `PublishingStep.copyFiles`
* add parameter `includingHidde: Bool` to functions `PublishingStep.copyResources` and `PublishingStep.copyFiles`
> Clean Output folder including hidden files

- Package.resolved
- Package.swift
- Tests/PublishTests/Tests/RSSFeedGenerationTests.swift
Update Publish’s dependencies to their latest versions:
- Ink `0.4.0`
- Plot `0.6.0`
- Sweep `0.4.0`
Also use Sweep’s new `firstSubstring` API.
> Swift package update

- Sources/Publish/Internal/MarkdownContentFactory.swift
- Tests/PublishTests/Tests/MarkdownTests.swift
Tiny tiny 1 line PR to use `file.nameExcludingExtension` as a fallback for `Content.title` if:
- There is no `title` in the Markdown metadata
- There is no implicit `h1` title in the file.
Unnecessary background: I'm using Publish to assemble a single page from one main index and a subfolder of things which get added to the main page. Imagine something like:
```
📂 Content/product/ ▼
📝 index.md
📂 features/ ▼
📝 00-Speed.md
📝 01-Flexibility.md
📝 02-Power.md
```
And within my custom Theme, I'd like to do something like:
```swift
.body(
.h1("Features"),
.forEach(
section.items.sorted{ $0.content.title < $1.content.title }
) { item in
Node.contentBody(item.content.body)
},
// ...
)
```
I'm using filenames to order the items, which is handy when browsing the files. I explicitly don't want to add …
> Use filename as fallback for Markdown content title

- Sources/Publish/API/Predicate.swift
- Sources/Publish/API/PublishingStep.swift
- Sources/Publish/Internal/RSSFeedGenerator.swift
- Tests/PublishTests/Tests/RSSFeedGenerationTests.swift
This change enables users to decide whether to include a given item in a generated RSS feed using a predicate, which can be very useful when wanting to conditionally decide which items that go into a certain feed.
> RSS: Enable filtering of items using a predicate

- Sources/Publish/API/ItemRSSProperties.swift
- Sources/Publish/API/PlotComponents.swift
- Tests/PublishTests/Tests/RSSFeedGenerationTests.swift
This change makes it possible to define a prefix and/or suffix that will get added to an item’s body when rendered within an RSS feed. This can, for example, be used to provide specific intro paragraphs for RSS items, to embed media players, and so on.
Just like the equivalent APIs for titles, these prefixes/suffixes are rendered as-is and are not converted to HTML automatically.
> RSS: Add APIs for defining a prefix and suffix for an item’s body

- Sources/Publish/API/PublishingStep.swift
- Sources/Publish/API/Section.swift
- Tests/PublishTests/Tests/ContentMutationTests.swift
This change adds a `PublishingStep` that makes it possible to conditionally remove items.
Coming from other static site generators, I have grown accustomed to writing posts labeled as drafts, which will be excluded from a build until marked as ready. This PR is meant to provide the capability to create such a workflow.
I use this feature for my site by adding an optional `draft: Bool?` item metadata property, and then conditionally run a step that removes such items from the build:
```swift
.if(CommandLine.arguments.contains("--removeDrafts"), .removeAllItems(matching: \.metadata.draft == true))
```
I then finish things off by passing a `--removeDrafts` flag when deploying my site.
> Add ability to remove items from a section

- Sources/Publish/API/ItemRSSProperties.swift
- Sources/Publish/API/PlotComponents.swift
- Sources/Publish/Internal/RSSFeedGenerator.swift
- Tests/PublishTests/Tests/RSSFeedGenerationTests.swift
This change makes it possible to specify a custom link for an item when it appears in an RSS feed. This is useful for RSS items that link to external resources, and enables those items to link directly to the target URL. However, the website’s own internal URL is still used as a default for each item’s GUID, in order to provide a stable identifier (as the external URL might change). That can always be customized using `rss.guid`, though.
> RSS: Add option to customize an item’s link

- Package.resolved
- Package.swift
- README.md
Swift version 5.2 (or later) is now required to use Publish.
> Bump Swift version to 5.2

- Sources/Publish/API/DeploymentMethod.swift
- Sources/Publish/API/PublishingContext.swift
- Tests/PublishTests/Tests/DeploymentTests.swift
This is a continuation of PR #74 and following the plan outlined [here](https://github.com/JohnSundell/Publish/pull/74#issuecomment-627321541)
- Added a branch parameter to Git/GitHub deployment method
- Enabled usage of custom dot files inside deployment methods
- Added a custom path for deployment folder content ( thanks @john-mueller )
All of this should enable more possibilities for deployments and custom deployment methods
> Extend Deployment Capabilities

- Sources/PublishCLI/main.swift
- Sources/PublishCLICore/CLI.swift
- Sources/PublishCLICore/ProjectGenerator.swift
- Sources/PublishCLICore/ProjectKind.swift
- Tests/PublishTests/Tests/CLITests.swift
This change makes it possible to run ‘publish new plugin’ in a folder to generate a plugin project. While plugins are just normal Swift packages, this makes it faster to get started building plugins.
The Swift tools version was also bumped to 5.2 for generated projects (to match Publish itself), and the minimum Publish version has been bumped to 0.6.0 (the latest release at this point).
> CLI: Add plugin project generation command

- Sources/Publish/API/PublishingStep.swift
- Sources/Publish/Internal/PodcastFeedGenerator.swift
- Tests/PublishTests/Tests/PodcastFeedGenerationTests.swift
This change enables a Predicate to be passed to the generatePodcastFeed publishing step, which lets the user conditionally decide which items to include in the feed. This feature was previously added to standard RSS feeds, but now podcast feeds also have the same capability.
> Enable filtering of podcast items using a predicate

- README.md
Current code formatting in the themes snippet requires horizontal scrolling. If it's slightly reformatted, horizontal scrolling can be avoided improving readability.
> Fix horizontal scrolling in README.md

- Sources/PublishCLI/main.swift
This file refers to Publish 0.6.0, which leads to generating new projects with templates that depend on 0.6.0. This doesn't seem to be right, as the latest version is 0.7.0.
> Fix incorrect version in PublishCLI/main.swift

- Sources/PublishCLICore/ProjectGenerator.swift
Hi,
Wanted to test Publish and wasn't very original in naming and run command `publish new` in folder called "Website".
Obviously it created `struct Website: Website`.
This PR changes protocol name to `Publish.Website`, if struct name is `Website`.
> Fix namespacing issue for websites with name "Website".

- Sources/Publish/API/DeploymentMethod.swift
- Tests/PublishTests/Tests/DeploymentTests.swift
When using the `.git` or `.github` deployment strategies with a custom branch specified (for example, `gh-pages`), the deployment will fail with the following error message:
```
[info] error: src refspec gh-pages does not match any
error: failed to push some refs to 'github.com:my-name/my-name.github.io.git'
```
(This error can be seen in [this GitHub action](https://github.com/schrismartin/schrismartin.github.io/runs/4135033142?check_suite_focus=true#step:3:223))
This occurs because, when creating the `.publish/GitDeploy` directory, the HTML is generated in the default created branch (on some computers, `master`, and in others `main`) rather than the branch specified in the `branch` parameter. 
This PR adds a single additional command to checkout the specified branch pulled from the …
> Checkout target deployment destination

- Sources/PublishCLICore/WebsiteRunner.swift
Since Publish now requires macOS 12, we can safely require Python 3 when using the CLI's `run` command to start a local web server.
> CLI: Always use Python 3

- Sources/Publish/API/Website.swift
- Allow Publish to run on [platforms](https://swiftwasm.org) which cannot support a `DispatchSemaphore`.
- Allow calling Publish from async contexts without the risk of deadlock.
- Keeping existing clients intact.
Adding alternative `async` versions of the `Website.publish` methods.
Compared with the approach of [replacing sync with async versions](https://github.com/JohnSundell/Publish/pull/141), this PR keeps all tests passing and *almost* doesn't break calling sites.
This is technically a breaking change but in a pretty minimal way, according to calling context:
- In a `synchronous` function, the sync version will be inferred as before - no change.
- In `main.swift` top-level code, the sync version will be inferred as before (adding `await` in the call will result in a warning).
- In …
> Add public async versions of `publish` method
